services:
  discord-bot-template:
    image: ghcr.io/e4-discord/discord-bot-template:dev
    container_name: discord-bot-template-dev
    environment:
      PYTHON_FILE_NAME: app
    secrets:
      - source: discord_bot_template_dev_token
        target: discord_bot_token
    restart: always

secrets:
  discord_bot_template_dev_token:
    external: true
